import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { HomeSidebar } from "@/components/home/home-sidebar";


const archivo = Archivo({
  variable: "--font-archivo-sans",
  subsets: ["latin"],
});
const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${archivo.variable} antialiased`}
      >
        <SidebarProvider>
          <HomeSidebar />
          <SidebarInset>

            <Header />
            <main className="mt-14 container mx-auto px-4 py-2 bg-zinc-50">
              {children}
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
